<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- MassTransit -->
    <PackageVersion Include="MassTransit.EntityFrameworkCore" Version="8.5.2" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="8.5.4" />
    <!-- EF Core + Npgsql -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <!-- Microsoft.Extensions.* -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.7" />
    <!-- Инфраструктура/инструменты -->
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Telegram.Bot" Version="22.6.0" />
  </ItemGroup>
</Project>
