// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpendingTrackerService.Database;

#nullable disable

namespace SpendingTrackerService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250911190523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpendingTrackerService.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserId", "Id")
                        .HasName("AK_categories_user_id_id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_categories_user_name_active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_categories_user_request")
                        .HasFilter("\"RequestId\" IS NOT NULL");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Category_NotSystemDeleted", "NOT (\"IsSystem\" AND \"IsDeleted\")");
                        });
                });

            modelBuilder.Entity("SpendingTrackerService.Database.Entities.ExpenseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,2)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AddedAtUtc");

                    b.HasIndex("UserId", "CategoryId");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique();

                    b.HasIndex("UserId", "CategoryId", "AddedAtUtc");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("SpendingTrackerService.Database.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("SpendingTrackerService.Database.Entities.CategoryEntity", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId", "CategoryId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SpendingTrackerService.Database.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
