<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-StatisticsService-94407be6-dec3-40be-abfa-a755ab3e9865</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\SharedTypes\SharedTypes.csproj" />
    </ItemGroup>

</Project>
