// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StatisticsService.Infrastructure.Persistence;

#nullable disable

namespace StatisticsService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019190307_UpdateDataAndAddStats")]
    partial class UpdateDataAndAddStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StatisticsService.Database.Entities.StatsDailyByCategoryEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AmountTotal")
                        .HasColumnType("numeric(19,2)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ExpensesCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxExpenseAmount")
                        .HasColumnType("numeric(19,2)");

                    b.Property<string>("MaxExpenseNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "Day", "CategoryId");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_user_stats_dbc_day");

                    b.HasIndex("UserId", "Day")
                        .IsDescending()
                        .HasDatabaseName("ix_user_stats_dbc_user_day_desc");

                    b.HasIndex("UserId", "Day", "AmountTotal")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_user_stats_dbc_user_day_amount_desc");

                    b.ToTable("user_stats_daily_by_category", (string)null);
                });

            modelBuilder.Entity("StatisticsService.Database.Entities.StatsDailyEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("AmountTotal")
                        .HasColumnType("numeric(19,2)");

                    b.Property<int>("ExpensesCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxExpenseAmount")
                        .HasColumnType("numeric(19,2)");

                    b.Property<string>("MaxExpenseNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "Day");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_user_stats_daily_day");

                    b.HasIndex("UserId", "Day")
                        .IsDescending()
                        .HasDatabaseName("ix_user_stats_daily_user_day_desc");

                    b.ToTable("user_stats_daily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
