<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-TgApiService-cd1b5c5a-bf8e-4e3e-a88d-e3a6552a85bc</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.RabbitMQ" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Telegram.Bot" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Shared\SharedTypes\SharedTypes.csproj" />
    </ItemGroup>

</Project>
